[package]
name = "mmml-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }

[profile.release]
lto = false
codegen-units = 1
opt-level = "s"
panic = "abort"
strip = "debuginfo"
