name: Rust compile & test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build (Debug)
      run: cargo build --verbose
    - name: Build (Release)
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Debug Linux Build
      uses: actions/upload-artifact@v4
      with:
        name: µMML Compiler Linux (Debug)
        path: ./target/debug/mmml-compiler
        retention-days: 7
    - name: Upload Release Linux Build
      uses: actions/upload-artifact@v4
      with:
        name: µMML Compiler Linux (Debug)
        path: ./target/release/mmml-compiler
        retention-days: 7
